# Generated by Django 3.1.7 on 2021-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210513_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='DOB',
        ),
        migrations.AddField(
            model_name='contact',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='roll',
            field=models.CharField(default='', max_length=18),
        ),
    ]
