# Generated by Django 3.1.7 on 2021-05-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210513_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='dob',
        ),
    ]
